[tools]
flutter = "3.38.1-stable"
"gem:cocoapods" = "1.16.2"
java = "zulu-21"
ruby = "3.4.7"
gitleaks = "8.29.1"
lefthook = "2.1.1"

[tasks.install]
run = """
mise install
lefthook install --reset-hooks-path
"""