name: flutter_engineer_codecheck
description: A new Flutter project.

version: 1.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.6.1
  riverpod_generator: ^2.3.5
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.7.0
  retrofit: ^4.4.2
  auto_route: ^9.2.2
  app_links: ^6.3.3
  alchemist: ^0.11.0
  very_good_analysis: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <6.0.0"
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.7
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true